### PR TITLE
Remove Bower and move NPM

### PR DESCRIPTION
**Pull request by jezhodges**
Bower is deprecated.

- Removes the bower configs (was never published to Bower anyway)
- Update settings ready for NPM publishing

### CODE REVIEW

**Comment by jezhodgesbbc** [comment]
Dependant on https://github.com/bbc/gs-sass-tools/pull/36

**Review by jasonwilliams — APPROVED** [review]

**Comment by amosuro** [comment]
Is there a plan to merge this change at some point? We'd very much like to use this but can't justify adding bower just to use this dependancy. If there is any way we can help push this forward let me know!

**Comment by Jayflux** [comment]
@amosuro  im going to try and catch up with the maintainers of this project and push this forward in the next couple of weeks

**Comment by jezhodgesbbc** [comment]
@amosuro currently waiting on getting this project setup with Travis CI so that we can automatically build and push to NPM on future merges.

**Comment by amosuro** [comment]
Thanks for the update, I'll keep an eye on this PR. For the time being we
will use bower

**Comment by mintuz** [comment]
The question I have around this is what benefit does it provide by removing the bower.json file. 

My thoughts are we shouldn't remove the bower config from the repo, projects are pulling it in via bower and the github url internally. Without the config it will fail to install correctly.

Now in a ideal world we would all use npm however internally Morph doesn't support the latest version of npm where it provides a flat dependency tree so with nested modules, the relative paths to the bower_components folder changes.

**Comment by jezhodgesbbc** [comment]
@mintuz completely agree. I was going to update this PR to add the bower stuff back in.

**Pull request closed without merging**
