### PR TITLE
Updates Tamil, Sinhala and Bengali font sizes to UX specification

### PR DESCRIPTION
**Pull request by pvaliani**
This pr updates font configurations for Bengali, Tamil and Sinhala services relating to the following issue:

https://github.com/bbc/simorgh/issues/9435

Font size UX specification info (request for access):
https://docs.google.com/spreadsheets/d/1ZXxajDkmbenCdYWtTBkDogRqi9a3-O4tsXUK7nvDrWU/edit#gid=771505033

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]
👍

**Comment by benswatson** [comment]
Does this need a version bump?

https://github.com/bbc/grandstand/blob/master/bower.json#L20
https://github.com/bbc/grandstand/blob/master/package.json

**Comment by pvaliani** [comment]
> Does this need a version bump?
> 
> https://github.com/bbc/grandstand/blob/master/bower.json#L20
> https://github.com/bbc/grandstand/blob/master/package.json

yes good spot. Have updated in a new commit!

**Comment by benswatson** [comment]
> > Does this need a version bump?
> > https://github.com/bbc/grandstand/blob/master/bower.json#L20
> > https://github.com/bbc/grandstand/blob/master/package.json
> 
> yes good spot. Have updated in a new commit!

Thanks! Is package.json's version field redundant with bower.json?

**Comment by HarveyPeachey** [comment]
> > > Does this need a version bump?
> > > https://github.com/bbc/grandstand/blob/master/bower.json#L20
> > > https://github.com/bbc/grandstand/blob/master/package.json
> > 
> > 
> > yes good spot. Have updated in a new commit!
> 
> Thanks! Is package.json's version field redundant with bower.json?

Nope, I've now updated the `package.json` @benswatson

**Review by benswatson — APPROVED** [review]

**Pull request merged**
