### PR TITLE
Add script for gujarati service

### PR DESCRIPTION
**Pull request by andela-amagana**
Add gujarati script for use by the gujarati service.

[PR - ws-alephamp-queue-renderer](https://github.com/bbc/ws-alephamp-queue-renderer/pull/365)
[WS2020-704](https://jira.dev.bbc.co.uk/browse/WS2020-704)

### CODE REVIEW

**Comment by andela-amagana** [comment]
Hello @sareh 
I have removed the placeholder files for `ethiopic`.
Can I revert [Add ethiopic script for amharic and tigrinya](https://github.com/bbc/grandstand/pull/82) and by extension grandstand back to `5.0.1`?

**Comment by pjlee11** [comment]
Hey @andela-amagana I've just been speaking with @hindsc52  and I think we might still need these script configs.

In the PAL gujarati fallbacks to hindi https://github.com/BBC-News/responsive-news/blob/develop/tabloid/webapp/static/sass/main/services/gujarati/_config.scss#L3 whereas in GS I think it will fallback to latin which would be wrong
I think we need to handle a different fallback in GS or duplicate the hindi values in the gujarati config

**Comment by andela-amagana** [comment]
Hey @pjlee11 to be clear, you use the script type to select the GS script to import and in the case that script type doesn't exist, you use the fallback script to import the fallback script. Am I correct?
If that's, the case should we keep the placeholder scripts since having a mapper in the
(renderer)[https://github.com/bbc/ws-alephamp-queue-renderer/blob/add-font-for-gujarati/src/lib/service/static/config.rb#L24] is going to be temporary and will need changing once the service overrides are availed?

**Comment by andela-amagana** [comment]
Please take a look at the `ethiopic` script [here](https://github.com/bbc/grandstand/pull/82) for context on why I removed the placeholder scripts.

**Comment by pjlee11** [comment]
Let's catch up on this tomorrow as I think we might to do some further work unless I'm misunderstanding something.

**Comment by pjlee11** [comment]
This PR affectively reverts #82.
Further work to correctly handle the ethiopic script will be done as part of https://jira.dev.bbc.co.uk/browse/WS2020-743

**Pull request merged**
